### PR TITLE
add support to use MQTT to get data when running node-server eternally

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by mpvader** [comment]
It seems to re-request each value individually. Is that really necessary? From performance point of view it’s the worst that can be done.

**Comment by sbender9** [comment]
I don’t see a way to request them all at once. The fit page says wildcards are not supported.

**Comment by sbender9** [comment]
Actually it looks like when you subscribe to a specific device, it sends all the fields. Let me try subscribing again instead of requesting them individually.

**Comment by mpvader** [comment]
as discussed elsewhere: I've applied (only) the first two commits, and left the re-requesting out for now.

thanks, again!

**Pull request closed without merging**
